server:
  port: 8080
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ephemeral: false
    gateway:
      #跨域
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      discovery:
        locator:
          #开启以服务id去注册中心获取转发地址
          enabled: true
      #路由策略
      routes:
          #路由id
        - id: service-user
          #转发  lb自带负载均衡
          uri: lb://service-user
          #匹配原则
          predicates:
            - Path=/user/**

        - id: service-role
          uri: lb://service-role
          predicates:
            - Path=/role/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alibaba?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 500MB


mybatis-plus:
  type-aliases-package: com.zmh.gateway.enty
  mapper-locations: classpath:/mapping/*.xml